--- #YAML:1.0
name:               Test-Tail-Multi
version:            0.06
abstract:           ~
author:
    - Joe McMahon <joe@corp.yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Tail:    0
    Test::Simple:  0.98
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
